{************************************************}
{                                                }
{   ObjectWindows Demo                           }
{   Copyright (c) 1992 by Borland International  }
{                                                }
{************************************************}

const
	cm_FilePrint = 105;
	cm_FileSetup = 107;
	cm_About = 201;
	cm_Pen = 200;
	cm_PalShow = 301;
	cm_PalHide = 302;
