Algoritmica si programare - semestrul II 1998/1999

1. Tipul record
2. Tipul fisier
3. Structuri dinamice de date. Pointeri
4. Liste simplu inlantuite
5. Stive si cozi
6. Arbori binari. Algoritmi de parcurgere (traversare) a arborilor
   binari
7. Algoritmi de cautare si sortare
8-9. Grafica
10-14 Metode de proiectare a algoritmilor
       - elaborarea algoritmilor; proiectarea top-down;
         proiectarea modulara; proiectarea structurata
       - metoda backtracking (generarea de combinari, aranjamente,
         permutari, problema celor 8 dame, problema pieselor
         de domino, problema submultimilor cu suma data,
         problema colorarii hartilor)
       - metoda branch and bound (problema canibalilor,
         problema caprelor)
       - metoda greedy (problema rucsacului, determinarea numerelor
         prime)
       - alte metode
          - programarea dinamica (produsul optim de matrice)
          - metoda divizarii (problema intervalelor, turnurile
            din Hanoi)
          - metoda euristica (problema comis-voiajorului)
