unit mfilec;

interface

const

	tbHelp	=	501;
	tbFileOpen	=	502;
	tbFileSave	=	503;

	tbClipCut	=	504;
	tbClipCopy	=	505;
	tbClipPaste	=	506;
	tbEditCut	=	504;
	tbEditCopy	=	505;
	tbEditPaste	=	506;
	cm_Help	=	998;
	tbExit	=	508;
	cm_SaveState	=	200;
	cm_RestoreState	=	201;
	cm_HorizontalToolbar	=	210;
	cm_RightVerticalToolbar	=	211;
	cm_LeftVerticalToolbar	=	212;
implementation

end.
