Operatii implementate pentru toate stivele:
  Vida
  Plina
  Push
  Pop
  Top
  Init
  Term
  List

Stiva1P - stiva implementata ca tablou, varianta procedurala
          S este variabila globala
Stiva2P - stiva implementata ca lista inlantuita, varianta procedurala
          S este variabila globala
Stiva1M - stiva implementata ca tablou, varianta modulara (UStiva1M)
          S este variabila globala
Stiva2M - stiva implementata ca lista inlantuita, varianta modulara
          (UStiva2M)
          S este variabila globala
Stiva3M - stiva implementata ca tablou de pointeri la element,
          varianta modulara (UStiva3M)
          S este variabila globala
Stiva4M - stiva implementata ca lista inlantuita de pointeri la element,
          varianta modulara (UStiva4M)
          S este variabila globala
Stiva5M - stiva implementata ca tablou dinamic si flexibil de pointeri
          la element, varianta modulara (UStiva5M)
          S este variabila globala
Toate programele apeleaza procedurile
  - Operatii
  - Run
care sunt incluse in fisierele
  - operatp.pas
  - stivap.run

Stiva1  - stiva implementata ca tablou, varianta procedurala
          S este parametru al fiecarei operatii
Stiva2  - stiva implementata ca lista inlantuita, varianta procedurala
          S este parametru al fiecarei operatii
Stiva1U - stiva implementata ca tablou, varianta modulara (UStiva1)
          S este un parametru al fiecarei operatii
Stiva2U - stiva implementata ca lista inlantuita, varianta modulara
          (UStiva2)
          S este un parametru al fiecarei operatii
Stiva3U - stiva implementata ca tablou de pointeri la element,
          varianta modulara (UStiva3)
          S este un parametru al fiecarei operatii
Stiva4U - stiva implementata ca lista inlantuita de pointeri la element,
          varianta modulara (UStiva4)
          S este un parametru al fiecarei operatii
Stiva5U - stiva implementata ca tablou dinamic si flexibil de pointeri
          la element, varianta modulara (UStiva5)
          S este un parametru al fiecarei operatii
Toate programele apeleaza procedurile
  - Operatii
  - Run
care sunt incluse in fisierele
  - operatm.pas
  - stivam.run
