{************************************************}
{                                                }
{   ObjectWindows Grep Demo Constants Unit       }
{   Copyright (c) 1992 by Borland International  }
{                                                }
{************************************************}

unit OGConst;

interface

const
        idBeginSearch   =       100;
        idDirectory     =       101;
        idFileMask      =       102;
        idExpression    =       103;
        idCaseSensitive =       104;
        idRecurseDirs   =       105;
        idFileList      =       106;
        idStatus        =       107;

        idGrepButton    =       200;

implementation

end.  
