Operatii implementate pentru toate cozile:
  Vida
  Plina
  Adauga
  Scoate
  Primul
  Ultimul
  Init
  Term
  List

Coada1P - Coada implementata ca tablou, varianta procedurala
          C este variabila globala
Coada2P - Coada implementata ca lista inlantuita, varianta procedurala
          C este variabila globala
Coada1M - Coada implementata ca tablou, varianta modulara (UCoada1M)
          C este variabila globala
Coada2M - Coada implementata ca lista inlantuita, varianta modulara
          (UCoada2M)
          C este variabila globala
in proiect (neterminate)
Coada3M - Coada implementata ca tablou de pointeri la element,
          varianta modulara (UCoada3M)
          C este variabila globala
Coada4M - Coada implementata ca lista inlantuita de pointeri la element,
          varianta modulara (UCoada4M)
          C este variabila globala
Coada5M - Coada implementata ca tablou dinamic si flexibil de pointeri
          la element, varianta modulara (UCoada5M)
          C este variabila globala
Toate programele apeleaza procedurile
  - Operatii
  - Run
care sunt incluse in fisierele
  - operatp.pas
  - Coadap.run

Coada1  - Coada implementata ca tablou, varianta procedurala
          C este parametru al fiecarei operatii
Coada2  - Coada implementata ca lista inlantuita, varianta procedurala
          C este parametru al fiecarei operatii
Coada1U - Coada implementata ca tablou, varianta modulara (UCoada1)
          C este un parametru al fiecarei operatii
Coada2U - Coada implementata ca lista inlantuita, varianta modulara
          (UCoada2)
          C este un parametru al fiecarei operatii
(in proiect)
Coada3U - Coada implementata ca tablou de pointeri la element,
          varianta modulara (UCoada3)
          C este un parametru al fiecarei operatii
Coada4U - Coada implementata ca lista inlantuita de pointeri la element,
          varianta modulara (UCoada4)
          C este un parametru al fiecarei operatii
Coada5U - Coada implementata ca tablou dinamic si flexibil de pointeri
          la element, varianta modulara (UCoada5)
          C este un parametru al fiecarei operatii
Toate programele apeleaza procedurile
  - Operatii
  - Run
care sunt incluse in fisierele
  - operatm.pas
  - Coadam.run
