{************************************************}
{                                                }
{   Resource Workshop Demo unit                  }
{   Copyright (c) 1992 by Borland International  }
{                                                }
{************************************************}

unit BitBtnCo;

interface

const

	idButtonStyle	=	100;
	idCaption	=	100;
	idControlId	=	101;
	idTabStop	=	102;
	idDisabled	=	103;
	idGroup         =	104;
	idDefaultButton	=	105;
	idPushButton	=	106;
	btDisableBits   =       100;
	btDefBits	=	101;
	btUndefBits	=	102;
	crDefCurs	=	100;
	crUndefCurs	=	101;

implementation

end.
