{************************************************}
{                                                }
{   Resource Workshop Demo                       }
{   Copyright (c) 1992 by Borland International  }
{                                                }
{************************************************}

unit RWPDemoC;

interface

const
  acc_Main                   =  100;
  bmp_StatusBar              =  101;
  bmp_StatusLine             =  100;
  cm_About_RWP               =  145;
  cm_All                     =  121;
  cm_Blue                    = 1102;
  cm_By                      =  123;
  cm_Circle                  = 1000;
  cm_ClearShape              = 1200;
  cm_Directories             =  151;
  cm_Glossary                =  143;
  cm_Green	                 = 1101;
  cm_Index                   =  141;
  cm_Mouse                   =  153;
  cm_New                     =  100;
  cm_Normal                  = 1001;
  cm_Open                    =  102;
  cm_Options_Open            =  154;
  cm_Options_Save            =  155;
  cm_Options_SaveAs          =  156;
  cm_Preferences             =  152;
  cm_Print	                 =  105;
  cm_Rectangle               = 1001;
  cm_Red	                 = 1100;
  cm_Save                    =  103;
  cm_SaveAs                  =  104;
  cm_Some                    =  122;
  cm_Thick                   = 1002;
  cm_Thin                    = 1000;
  cm_Topic_Search            =  142;
  cm_Using_Help              =  144;
  dlg_About                  =  104;
  dlg_FileNew                =  106;
  dlg_Mouse                  =  105;
  dlg_MouseDialog            =  105;
  dlg_Open                   =  100;
  dlg_Options_Directories    =  109;
  dlg_Options_Open           =  107;
  dlg_Options_SaveAs         =  108;
  dlg_Preferences            =  103;
  dlg_Print                  =  102;
  dlg_SaveAs                 =  101;
  ico_RWPDemo                =  100;
  id_all                     =  212;
  id_ClearWindow             =  229;
  id_config_file_directory   =  224;
  id_Copies                  =  211;
  id_current_directory       =  223;
  id_Desktop                 =  227;
  id_Editor_files            =  225;
  id_Environment             =  226;
  id_From                    =  214;
  id_Graph                   =  207;
  id_GraphicDirectory        =  221;
  id_Graphics                =  231;
  id_help                    =	998;
  id_horiz_scoller           =  231;
  id_Include_Directory       =  220;
  id_InverseColor            =  230;
  id_Library_Directory       =  221;
  id_none                    =  222;
  id_nothing                 =  228;
  id_open1                   =  100;
  id_open2                   =  101;
  id_Partial                 =  213;
  id_Print                   =  217;
  id_printer                 =  216;
  id_Printer_setup           =  218;
  id_Process_it              =  230;
  id_Reverse_mouse_buttons   =  232;
  id_RWP_Directory           =  219;
  id_Scribble                =  206;
  id_ScribbleDirectory	     =  219;
  id_Text                    =  205;
  id_TextDirectory           =  220;
  id_To                      =  215;
  id_TopicSearch             =  229;
  men_Main                   =  100;
  sth_Edit                   =   15;
  sth_EditClear              =   13;
  sth_EditCopy               =   11;
  sth_EditCut                =   10;
  sth_EditDelete             =   14;
  sth_EditPaste              =   12;
  sth_EditUndo               =    9;
  sth_EnvironmentMouse       =   27;
  sth_EnvironmentPreferences =   26;
  sth_File                   =    8;
  sth_FileExit               =  100;
  sth_FileNew                =    1;
  sth_FileOpen               =    2;
  sth_FilePrint              =    5;
  sth_FileSave               =    3;
  sth_FileSaveAs             =    4;
  sth_Help                   =   40;
  sth_HelpAbout              =   39;
  sth_HelpGlossary           =   37;
  sth_HelpIndex              =   34;
  sth_HelpSearch             =   36;
  sth_HelpTopic              =   35;
  sth_HelpUsing              =   38;
  sth_Mouse                  =   13;
  sth_Open                   =    2;
  sth_Option                 =   25;
  sth_OptionsDirectory       =   20;
  sth_OptionsEnvironment     =   21;
  sth_OptionsOpen            =   22;
  sth_Options_Open           =    6;
  sth_OptionsSave            =   23;
  sth_OptionsSaveAs          =   24;
  sth_Preferences            =   14;
  sth_Print                  =    5;
  sth_Save                   =    3;
  sth_SaveAs                 =    4;
  sth_View                   =   19;
  sth_ViewAll                =   16;
  sth_ViewBy                 =   18;
  sth_ViewSome               =   17;
  sth_Window                 =   33;
  sth_WindowTile             =   28;
  sth_WindowCascade          =   29;
  sth_WindowArrange          =   30;
  sth_WindowIcon             =   31;
  sth_WindowCloseAll         =   32;
  ScribbleWindow             =  100;
  FileWindow                 =  101;
  GraphWindow                =  102;
  Id_Splash	                 =  102;

  ste_InvalidGraphFileMsg      = 130;
  ste_InvalidGraphFileTitle    = 131;
  ste_InvalidScribbleFileMsg   = 132;
  ste_InvalidScribbleFileTitle = 133;

implementation
end.
