{************************************************}
{                                                }
{   ObjectWindows Demo                           }
{   Copyright (c) 1992 by Borland International  }
{                                                }
{************************************************}

const
  cm_New    = 101;
  cm_Open   = 102;
  cm_Save   = 103;
  cm_SaveAs = 104;
  cm_Print  = 105;
  cm_Setup  = 106;
  cm_Pen    = 201;
  cm_About  = 202;
  cm_Undo   = 203;

  cm_ShowPal = 801;
  cm_HidePal = 802;
