Metode numerice si biblioteci de programe

Semestrul II 1998/1999

1. Programare modulara. Exemple
2-4. Abstractizarea datelor.
     Tipuri numerice extinse: complex, rational, intreg in precizie
     marita si cu operatii in baza p
3. Tipuri de date utilizator
5-7. Programarea orientata pe obiecte
     Concepte generale
     Programarea orientata pe obiecte in Turbo Pascal
8. Grafica in Turbo Pascal
9. Calcule numerice folosind calculatorul: erori, performante,
   limite
10. Functii matematice. Implementarea lor in Pascal
11. Determinarea radacinilor unui polinom
12 Rezolvarea ecuatiilor neliniare
13-14. Rezolvarea sistemelor de ecuatii liniare.
