const
  sd_FileOpen = $7FFF;          { Use default file open template }
  sd_FileSave = $7FFE;          { Use default file save template }
  sd_WNFileOpen = $7F00;        { Normal file open template }
  sd_WNFileSave = $7F01;        { Nomral file save template }
  sd_BCFileOpen = $7F03;        { BWCC file open template }
  sd_BCFileSave = $7F04;        { BWCC file save template }

const
  id_FName = 100;
  id_FPath = 101;
  id_FList = 102;
  id_DList = 103;

